/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package money.scheduler;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MoneySchedulerTest {
    @Test void testSomeLibraryMethod() {
        MoneyScheduler classUnderTest = new MoneyScheduler();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
